### ISSUE TITLE
Partial function application

### ISSUE THREAD

**Issue by alexandru** [miniboxing/miniboxing-plugin#111] opened 2014-06-30 12:24 UTC
Given this sample:

``` scala
import scala.concurrent.{ExecutionContext, Future}

trait Sample[@miniboxed T] {
  def process(elem: T): Future[Unit]

  def apply(elem: T)(implicit ec: ExecutionContext): Unit = {
    process(elem).onSuccess {
      case () => println("Done")
    }
  }
}
```

Compilation fails with:

```
[error] .../Sample.scala:25: [ occured while creating miniboxed method apply_J in trait Sample_J ]
[error] type mismatch;
[error]  found   : x1.type (with underlying type Unit)
[error]  required: A1
[error]     process(elem).onSuccess {
[error]                             ^
[error] one error found
```

Same sample succeeds if `Future.onSuccess` is replaced with `Future.onComplete` which doesn't take a `PartialFunction` as argument.

**Comment by VladUreche** [comment] 2014-06-30 13:41
It looks like specialization is also affected: https://issues.scala-lang.org/browse/SI-8694

**Comment by alexandru** [comment] 2014-06-30 13:50
For `@specialized` the bug may have already been filled. This issue looks similar: https://issues.scala-lang.org/browse/SI-8633

BTW, is this something that monoboxing can fix - i.e. whose fault is it? :-)

I'm thinking that if this can't be fixed from the monoboxing plugin (a possibility I'm thinking of since Scala's specialization is also affected), then maybe it could generate a more helpful error message, because from a usability perspective a limitation is worse when the user doesn't know it encountered a limitation.

**Comment by VladUreche** [comment] 2014-06-30 14:10
> For @specialized the bug may have already been filled. This issue looks similar: https://issues.scala-lang.org/browse/SI-8633

Thanks, marked the bug I created as a duplicate of SI-8633. I should have searched before filing the bug...

> BTW, is this something that monoboxing can fix - i.e. whose fault is it? :-)

I don't know, I'm looking into it now. Seems SI-8633 is better minimized, so I will start from there.

> I'm thinking that if this can't be fixed from the monoboxing plugin (a possibility I'm thinking of since Scala's specialization is also affected), then maybe it could generate a more helpful error message, because from a usability perspective a limitation is worse when the user doesn't know it encountered a limitation.

Good point. I'm still hoping the bug can be fixed, but I'll improve the error message to explain what's happening anyway.

**Comment by VladUreche** [comment] 2014-06-30 16:34
Further reduced:

```
package miniboxing.tests.compile.bug111

class Foo[@miniboxed T] {
  def foo(x: T) = {
    def applyOrElse[A1 <: Unit, B1 >: Unit](x1: A1, default: A1 => B1): B1 = x1.asInstanceOf[Unit] match {
      case () => ()
      case _ => default.apply(x1)
    }
  }
}
```

The bug is an interaction between the following elements:
- the `PartialFunction` desugaring naming scheme
- the pattern matching translation naming scheme
- the name-based resolution in duplicator in both specialization and miniboxing

User code cannot trigger the bug directly, it needs at least the pattern matcher to transform the code (the reduced example only requires the pattern matcher). For example, if you replace the code in the example from `x1` to `x2`, then it complies successfully.

**Closed as completed** 2014-06-30 20:07 UTC
Labels: bug
